# Site settings
title: Sarah Dougan | Freelance web designer
email: sarah@dougan.me
description: "Freelance web designer and devloper, specilising in UI/UX"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: mrsdougan
github_username:  mrsdougan

# Build settings
markdown: kramdown
permalink: pretty
